### ISSUE TITLE
Recommended kernel extensions

### ISSUE THREAD

**Issue by Thireus** [peerchemist/Peerbox#13]
# sysctl net.ipv4.conf.default.send_redirects
	net.ipv4.conf.default.send_redirects = 1

Should be set to 0.

	# sysctl net.ipv4.conf.all.log_martians
	net.ipv4.conf.all.log_martians = 0

Should be set to 1.

	# sysctl net.ipv4.conf.default.secure_redirects
	net.ipv4.conf.default.secure_redirects = 1

Should be set to 0.

**Comment by peerchemist** [comment]
Most of this is defined in iptables rules, but ok I will test and implement.
