### ISSUE TITLE
Sha256 checksum missing

### ISSUE THREAD

**Issue by Thireus** [peerchemist/Peerbox#17]
The new website design is great! Although, the sha256 checksum is missing for the package that we are downloading. I think it would be great to put it under the "Download" button but also to post it on Twitter (as a second distribution channel).

**Comment by peerchemist** [comment]
sha256sum is always posted on peercointalk.net
It would just clutter the website.

**Comment by Thireus** [comment]
It doesn't cost you anything to post the checksum there and it will help people who are not peercointalk members to find that sha256sum easily (copy paste from the download page on google to check if the checksum has been modified or not).

People are also reporting this issue here: http://www.peercointalk.org/index.php?topic=3654.msg37843#msg37843
