### ISSUE TITLE
peerbox user

### ISSUE THREAD

**Issue by peercoinops** [peerchemist/Peerbox#33]
Peerbox user (maybe "peerbox"?) so that the process runs as non-root system account. sudo access only to start,stop, and restart ppcoind daemon.

All processes, folders, configuration should also be owned by this system account.

**Comment by peerchemist** [comment]
Can you explain what is the problem here?

**Comment by peercoinops** [comment]
For the postinst script, creating a user 'peerbox' similar to how postgres user is created

https://github.com/petere/postgresql-common/blob/74c810d1cedf8766a54e68623d176b5147d532dd/debian/postgresql-common.postinst#L54

**Comment by peercoinops** [comment]
Then running setuid and setguid on the peerbox script so it always runs as user peerbox

**Comment by peercoinops** [comment]
In peercoin_rpc.py there is a call to getpass. So if try to run as sudo this call would fail, though ppcoind would still start as peerbox user.

> 
    with open('/home/{0}/.ppcoin/ppcoin.conf'.format(getpass.getuser()), 'r') as conf:

**Comment by peercoinops** [comment]
Another thing with this change is that when running peerbox it should be ran as the peerbox user, otherwise it won't be able to access the ppcoin configuration.

Have to think more about it.
