### ISSUE TITLE
Starting Peerbox issue 

### ISSUE THREAD

**Issue by gotqn** [peerchemist/Peerbox#36]
I am trying to create raspberry pie 3 node. I have follow the steps from the tutorial but when I type: 

`sudo peerbox -start`

I get the following error:

> Starting Peerbox...
> Traceback (most recent call last):
>   File "/usr/bin/peerbox", line 404, in <module>
>     node = Client(testnet=False)
>   File "/usr/lib/python2.7/dist-packages/peercoin_rpc/peercoin_rpc.py", line 32, in __init__
>     self.username, self.password = self.userpass() ## try to read from ~/.ppcoin
>   File "/usr/lib/python2.7/dist-packages/peercoin_rpc/peercoin_rpc.py", line 52, in userpass
>     with open('/home/{0}/.ppcoin/ppcoin.conf'.format(getpass.getuser()), 'r') as conf:
> IOError: [Errno 2] No such file or directory: '/home/root/.ppcoin/ppcoin.conf'

**Comment by peerchemist** [comment]
You are running it as root, it should be running as user "pi".

**Comment by gotqn** [comment]
I haven't got such user. I have deleted it and create another sudo user. If i run the program without sudo, nothing happened. I wait about 25-30 minutes and it still says `Starting Peerbox`

**Comment by peerchemist** [comment]
Create user "pi". Then reinstall peerbox to create all required files/folders.

`sudo apt-get install peerbox`

**Comment by peerchemist** [comment]
About such wait times, I will need more info. But first try this please.

**Comment by gotqn** [comment]
Thanks. It seem I am only able to start the peerbox with the pi user. Should I add this as request for development? In many raspberry tutorials it is shown how to create new user and delete the `pi` one. I guess this is limitation we do not need here.

**Comment by peerchemist** [comment]
Peerbox is designed to be username agnostic. However after creating new user you have to reinstall so proper configuration files get installed. Did you do that?

**Comment by gotqn** [comment]
Yes. I need to run sudo apt-get uninstall peerbox first, then install it using the pi username.
