### ISSUE TITLE
Force users to change their passwords after the first boot

### ISSUE THREAD

**Issue by Thireus** [peerchemist/Peerbox#9]
- root (/recovery mode) password must be changed (default is set to "root")
- sunny's password must be changed (default is set to "peerbox.me")

**Comment by peerchemist** [comment]
Fixed. Disabled root user, sunny user forced to change password upon first login.

https://github.com/peerchemist/Peerbox/commit/56c30bb6d417eb7ea3d6376cc5b595042b34a249
https://github.com/peerchemist/Peerbox/commit/909b4cce104b2b6774e8e1933cb510a4e9869d0b

**Comment by Thireus** [comment]
Awesome! Thank you peerchemist.
